### ISSUE TITLE
Sortable tab items

### ISSUE THREAD

**Issue by r03ert0** [ConnectProject/mavoix-panel#4]

**Comment by PieerotGG** [comment]
Fixed on [b4e73d9](https://github.com/ConnectProject/mavoix-panel/commit/b4e73d910769fa1ef7eb64ea9d82c31def4c96d1) and [51e389b](https://github.com/ConnectProject/mavoix-panel/commit/51e389b6be96a5a11f0dd784679cfe57d4bf153f)
