### ISSUE TITLE
"indisponible", "invisible", are properties of each image, not filtering criteria

### ISSUE THREAD

**Issue by r03ert0** [ConnectProject/mavoix-panel#65]
"indisponible", "invisible", are properties of each image, not filtering criteria
<img width="638" alt="Screenshot 2021-04-24 at 11 51 08" src="https://user-images.githubusercontent.com/2310732/115954849-77de5600-a4f3-11eb-93a0-2d88657e0326.png">

**Comment by narduin** [comment]
I changed those criteria for "public" and "private" images. Is is possible to show only the user's images or only the community's images?

**Comment by r03ert0** [comment]
it's not public and private:
"invisible" is an image that doesn't show in mavoix-app (because you don't want the kid to see it)
"indisponible" is an image that's marked with a big red dot, for example, because the kid is not allowed to have chocolate anymore, or it's not possible to go out at the moment, etc. Unline "invisible", the "indisponible" image does appear but it's not possible to use it.

**Comment by r03ert0** [comment]
additionally, at the moment, all images imported through upload, or acquired through the webcam are private and unavailable to other users of the app.

**Comment by narduin** [comment]
> "invisible" is an image that doesn't show in mavoix-app (because you don't want the kid to see it)
> "indisponible" is an image that's marked with a big red dot, for example, because the kid is not allowed to have chocolate anymore, or it's not possible to go out at the moment, etc. Unline "invisible", the "indisponible" image does appear but it's not possible to use it.
> additionally, at the moment, all images imported through upload, or acquired through the webcam are private and unavailable to other users of the app.

Yes I understand that. That's why I propose to offer the possibility to filter images based on who uploaded them (the user or the "community").
"Invisible“ and "indisponible" are still available when editing an image!

**Comment by r03ert0** [comment]
oh! ok.

But filtering by "indisponible" or "invisible" doesn't make sense.

More meaningful filtering criteria would be private/public, drawing/photograph, with/without background, colour/black&white, action/object, etc. More generally, the mechanism that would be nice to have is one that would allow us to give "tags" to pictures, and then filter by tag. We could automatically tag private/public, drawing/b&w, etc., but it would be nice to have the possibility to add additional tags in the future (even, potentially, allow users to add their own tags).

**Comment by narduin** [comment]
> But filtering by "indisponible" or "invisible" doesn't make sense.
> More meaningful filtering criteria would be private/public,

That's exactly what I did ^^

**Comment by r03ert0** [comment]
sorry :p
cool! could you paste an image?
can we close this issue then?

**Comment by narduin** [comment]
![Desktop-gallery--filter](https://user-images.githubusercontent.com/20305403/118684520-9558c400-b802-11eb-9f57-3b1d2ffb47be.jpg)
